#pragma once

using namespace ATL;

template <class T>
class CProxy_IADELLockCtlEvents : public IConnectionPointImpl<T, &__uuidof(_IADELLockCtlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
